// all languages supported

const languages = {
    en: {
        justNow: 'just now',
        minuteAgo: '1 minute ago',
        minutesAgo: 'minutes ago',
        hourAgo: '1 hour ago',
        hoursAgo: 'hours ago',
        yesterday: 'Yesterday',
        daysAgo: 'days ago',
        weekAgo: '1 week ago',
        weeksAgo: 'weeks ago',
        monthAgo: '1 month ago',
        monthsAgo: 'months ago',
        yearAgo: '1 year ago',
        yearsAgo: 'years ago'
    },
    es: {
        justNow: 'justo ahora',
        minuteAgo: 'hace 1 minuto',
        minutesAgo: 'hace minutos',
        hourAgo: 'hace 1 hora',
        hoursAgo: 'hace horas',
        yesterday: 'Ayer',
        daysAgo: 'hace días',
        weekAgo: 'hace 1 semana',
        weeksAgo: 'hace semanas',
        monthAgo: 'hace 1 mes',
        monthsAgo: 'hace meses',
        yearAgo: 'hace 1 año',
        yearsAgo: 'hace años'
    },
    fr: {
        justNow: 'juste maintenant',
        minuteAgo: 'il y a 1 minute',
        minutesAgo: 'il y a minutes',
        hourAgo: 'il y a 1 heure',
        hoursAgo: 'il y a heures',
        yesterday: 'Hier',
        daysAgo: 'il y a jours',
        weekAgo: 'il y a 1 semaine',
        weeksAgo: 'il y a semaines',
        monthAgo: 'il y a 1 mois',
        monthsAgo: 'il y a mois',
        yearAgo: 'il y a 1 an',
        yearsAgo: 'il y a ans'
    },
    de: {
        justNow: 'gerade eben',
        minuteAgo: 'vor 1 Minute',
        minutesAgo: 'vor Minuten',
        hourAgo: 'vor 1 Stunde',
        hoursAgo: 'vor Stunden',
        yesterday: 'Gestern',
        daysAgo: 'vor Tagen',
        weekAgo: 'vor 1 Woche',
        weeksAgo: 'vor Wochen',
        monthAgo: 'vor 1 Monat',
        monthsAgo: 'vor Monaten',
        yearAgo: 'vor 1 Jahr',
        yearsAgo: 'vor Jahren'
    },
    it: {
        justNow: 'proprio ora',
        minuteAgo: '1 minuto fa',
        minutesAgo: 'minuti fa',
        hourAgo: '1 ora fa',
        hoursAgo: 'ore fa',
        yesterday: 'Ieri',
        daysAgo: 'giorni fa',
        weekAgo: '1 settimana fa',
        weeksAgo: 'settimane fa',
        monthAgo: '1 mese fa',
        monthsAgo: 'mesi fa',
        yearAgo: '1 anno fa',
        yearsAgo: 'anni fa'
    },
    ja: {
        justNow: 'たった今',
        minuteAgo: '1 分前',
        minutesAgo: '分前',
        hourAgo: '1 時間前',
        hoursAgo: '時間前',
        yesterday: '昨日',
        daysAgo: '日前',
        weekAgo: '1 週間前',
        weeksAgo: '週間前',
        monthAgo: '1 か月前',
        monthsAgo: 'か月前',
        yearAgo: '1 年前',
        yearsAgo: '年前'
    },
    zh: {
        justNow: '刚刚',
        minuteAgo: '1 分钟前',
        minutesAgo: '分钟前',
        hourAgo: '1 小时前',
        hoursAgo: '小时前',
        yesterday: '昨天',
        daysAgo: '天前',
        weekAgo: '1 周前',
        weeksAgo: '周前',
        monthAgo: '1 个月前',
        monthsAgo: '个月前',
        yearAgo: '1 年前',
        yearsAgo: '年前'
    },
    ru: {
        justNow: 'только что',
        minuteAgo: '1 минуту назад',
        minutesAgo: 'минуты назад',
        hourAgo: '1 час назад',
        hoursAgo: 'часа назад',
        yesterday: 'Вчера',
        daysAgo: 'дней назад',
        weekAgo: '1 неделю назад',
        weeksAgo: 'недели назад',
        monthAgo: '1 месяц назад',
        monthsAgo: 'месяца назад',
        yearAgo: '1 год назад',
        yearsAgo: 'года назад'
    },
    pt: {
        justNow: 'agora mesmo',
        minuteAgo: 'há 1 minuto',
        minutesAgo: 'minutos atrás',
        hourAgo: 'há 1 hora',
        hoursAgo: 'horas atrás',
        yesterday: 'Ontem',
        daysAgo: 'dias atrás',
        weekAgo: 'há 1 semana',
        weeksAgo: 'semanas atrás',
        monthAgo: 'há 1 mês',
        monthsAgo: 'meses atrás',
        yearAgo: 'há 1 ano',
        yearsAgo: 'anos atrás'
    },
    ar: {
        justNow: 'الآن',
        minuteAgo: 'قبل دقيقة واحدة',
        minutesAgo: 'منذ دقائق',
        hourAgo: 'قبل ساعة واحدة',
        hoursAgo: 'منذ ساعات',
        yesterday: 'أمس',
        daysAgo: 'منذ أيام',
        weekAgo: 'قبل أسبوع واحد',
        weeksAgo: 'منذ أسابيع',
        monthAgo: 'قبل شهر واحد',
        monthsAgo: 'منذ أشهر',
        yearAgo: 'قبل عام واحد',
        yearsAgo: 'منذ أعوام'
    },
    hi: {
        justNow: 'अभी',
        minuteAgo: '1 मिनट पहले',
        minutesAgo: 'मिनट पहले',
        hourAgo: '1 घंटे पहले',
        hoursAgo: 'घंटे पहले',
        yesterday: 'बिता कल',
        daysAgo: 'दिन पहले',
        weekAgo: '1 हफ़्ते पहले',
        weeksAgo: 'हफ़्ते पहले',
        monthAgo: '1 महीने पहले',
        monthsAgo: 'महीने पहले',
        yearAgo: '1 साल पहले',
        yearsAgo: 'साल पहले'
    },
    tr: {
        justNow: 'şimdi',
        minuteAgo: '1 dakika önce',
        minutesAgo: 'dakika önce',
        hourAgo: '1 saat önce',
        hoursAgo: 'saat önce',
        yesterday: 'Dün',
        daysAgo: 'gün önce',
        weekAgo: '1 hafta önce',
        weeksAgo: 'hafta önce',
        monthAgo: '1 ay önce',
        monthsAgo: 'ay önce',
        yearAgo: '1 yıl önce',
        yearsAgo: 'yıl önce'
    },
    nl: {
        justNow: 'zojuist',
        minuteAgo: '1 minuut geleden',
        minutesAgo: 'minuten geleden',
        hourAgo: '1 uur geleden',
        hoursAgo: 'uren geleden',
        yesterday: 'Gisteren',
        daysAgo: 'dagen geleden',
        weekAgo: '1 week geleden',
        weeksAgo: 'weken geleden',
        monthAgo: '1 maand geleden',
        monthsAgo: 'maanden geleden',
        yearAgo: '1 jaar geleden',
        yearsAgo: 'jaren geleden'
    }
};

module.exports = languages;
