// all languages supported

const baseLanguage = {
    inSeconds: 'in {value} seconds',
    inMinutes: 'in {value} minutes',
    inHours: 'in {value} hours',
    inDays: 'in {value} days',
    inWeeks: 'in {value} weeks',
    inMonths: 'in {value} months',
    inYears: 'in {value} years',
    agoSuffix: ' ago',
    inPrefix: 'in '
  };
  
  const languages = {
    en: {
      ...baseLanguage,
      justNow: 'just now',
      secondsAgo: 'seconds ago',
      minuteAgo: '1 minute ago',
      minutesAgo: 'minutes ago',
      hourAgo: '1 hour ago',
      hoursAgo: 'hours ago',
      yesterday: 'Yesterday',
      daysAgo: 'days ago',
      weekAgo: '1 week ago',
      weeksAgo: 'weeks ago',
      monthAgo: '1 month ago',
      monthsAgo: 'months ago',
      yearAgo: '1 year ago',
      yearsAgo: 'years ago',
      justNowCompact: 'now'
    },
    es: {
      ...baseLanguage,
      justNow: 'justo ahora',
      secondsAgo: 'segundos atrás',
      minuteAgo: 'hace 1 minuto',
      minutesAgo: 'hace minutos',
      hourAgo: 'hace 1 hora',
      hoursAgo: 'hace horas',
      yesterday: 'Ayer',
      daysAgo: 'hace días',
      weekAgo: 'hace 1 semana',
      weeksAgo: 'hace semanas',
      monthAgo: 'hace 1 mes',
      monthsAgo: 'hace meses',
      yearAgo: 'hace 1 año',
      yearsAgo: 'hace años',
      justNowCompact: 'ahora',
      inSeconds: 'en {value} segundos',
      inMinutes: 'en {value} minutos',
      inHours: 'en {value} horas',
      inDays: 'en {value} días',
      inWeeks: 'en {value} semanas',
      inMonths: 'en {value} meses',
      inYears: 'en {value} años'
    },
    fr: {
      ...baseLanguage,
      justNow: 'à l\'instant',
      secondsAgo: 'secondes passées',
      minuteAgo: 'il y a 1 minute',
      minutesAgo: 'il y a minutes',
      hourAgo: 'il y a 1 heure',
      hoursAgo: 'il y a heures',
      yesterday: 'Hier',
      daysAgo: 'jours passés',
      weekAgo: 'il y a 1 semaine',
      weeksAgo: 'il y a semaines',
      monthAgo: 'il y a 1 mois',
      monthsAgo: 'il y a mois',
      yearAgo: 'il y a 1 an',
      yearsAgo: 'il y a ans',
      justNowCompact: 'mtn',
      inSeconds: 'dans {value} secondes',
      inMinutes: 'dans {value} minutes',
      inHours: 'dans {value} heures',
      inDays: 'dans {value} jours',
      inWeeks: 'dans {value} semaines',
      inMonths: 'dans {value} mois',
      inYears: 'dans {value} ans'
    },
    de: {
      ...baseLanguage,
      justNow: 'gerade eben',
      secondsAgo: 'Sekunden vergangen',
      minuteAgo: 'vor 1 Minute',
      minutesAgo: 'vor Minuten',
      hourAgo: 'vor 1 Stunde',
      hoursAgo: 'vor Stunden',
      yesterday: 'Gestern',
      daysAgo: 'Tage vergangen',
      weekAgo: 'vor 1 Woche',
      weeksAgo: 'vor Wochen',
      monthAgo: 'vor 1 Monat',
      monthsAgo: 'vor Monaten',
      yearAgo: 'vor 1 Jahr',
      yearsAgo: 'vor Jahren',
      justNowCompact: 'jetzt',
      inSeconds: 'in {value} Sekunden',
      inMinutes: 'in {value} Minuten',
      inHours: 'in {value} Stunden',
      inDays: 'in {value} Tagen',
      inWeeks: 'in {value} Wochen',
      inMonths: 'in {value} Monaten',
      inYears: 'in {value} Jahren'
    },
    it: {
      ...baseLanguage,
      justNow: 'proprio ora',
      secondsAgo: 'secondi fa',
      minuteAgo: '1 minuto fa',
      minutesAgo: 'minuti fa',
      hourAgo: '1 ora fa',
      hoursAgo: 'ore fa',
      yesterday: 'Ieri',
      daysAgo: 'giorni fa',
      weekAgo: '1 settimana fa',
      weeksAgo: 'settimane fa',
      monthAgo: '1 mese fa',
      monthsAgo: 'mesi fa',
      yearAgo: '1 anno fa',
      yearsAgo: 'anni fa',
      justNowCompact: 'ora',
      inSeconds: 'tra {value} secondi',
      inMinutes: 'tra {value} minuti',
      inHours: 'tra {value} ore',
      inDays: 'tra {value} giorni',
      inWeeks: 'tra {value} settimane',
      inMonths: 'tra {value} mesi',
      inYears: 'tra {value} anni'
    },
    ja: {
      ...baseLanguage,
      justNow: 'たった今',
      secondsAgo: '数秒前',
      minuteAgo: '1 分前',
      minutesAgo: '数分前',
      hourAgo: '1 時間前',
      hoursAgo: '数時間前',
      yesterday: '昨日',
      daysAgo: '数日前',
      weekAgo: '1 週間前',
      weeksAgo: '数週間前',
      monthAgo: '1 か月前',
      monthsAgo: '数か月前',
      yearAgo: '1 年前',
      yearsAgo: '数年前',
      justNowCompact: '今',
      inSeconds: '{value}秒後',
      inMinutes: '{value}分後',
      inHours: '{value}時間後',
      inDays: '{value}日後',
      inWeeks: '{value}週間後',
      inMonths: '{value}か月後',
      inYears: '{value}年後'
    },
    zh: {
      ...baseLanguage,
      justNow: '刚刚',
      secondsAgo: '几秒前',
      minuteAgo: '1 分钟前',
      minutesAgo: '几分钟前',
      hourAgo: '1 小时前',
      hoursAgo: '几小时前',
      yesterday: '昨天',
      daysAgo: '几天前',
      weekAgo: '1 周前',
      weeksAgo: '几周前',
      monthAgo: '1 个月前',
      monthsAgo: '几个月前',
      yearAgo: '1 年前',
      yearsAgo: '几年前',
      justNowCompact: '现在',
      inSeconds: '{value}秒后',
      inMinutes: '{value}分钟后',
      inHours: '{value}小时后',
      inDays: '{value}天后',
      inWeeks: '{value}周后',
      inMonths: '{value}个月后',
      inYears: '{value}年后'
    },
    ru: {
      ...baseLanguage,
      justNow: 'только что',
      secondsAgo: 'секунд назад',
      minuteAgo: '1 минуту назад',
      minutesAgo: 'минут назад',
      hourAgo: '1 час назад',
      hoursAgo: 'часов назад',
      yesterday: 'Вчера',
      daysAgo: 'дней назад',
      weekAgo: '1 неделю назад',
      weeksAgo: 'недель назад',
      monthAgo: '1 месяц назад',
      monthsAgo: 'месяцев назад',
      yearAgo: '1 год назад',
      yearsAgo: 'лет назад',
      justNowCompact: 'сейчас',
      inSeconds: 'через {value} секунд',
      inMinutes: 'через {value} минут',
      inHours: 'через {value} часов',
      inDays: 'через {value} дней',
      inWeeks: 'через {value} недель',
      inMonths: 'через {value} месяцев',
      inYears: 'через {value} лет'
    },
    pt: {
      ...baseLanguage,
      justNow: 'agora mesmo',
      secondsAgo: 'segundos atrás',
      minuteAgo: '1 minuto atrás',
      minutesAgo: 'minutos atrás',
      hourAgo: '1 hora atrás',
      hoursAgo: 'horas atrás',
      yesterday: 'Ontem',
      daysAgo: 'dias atrás',
      weekAgo: '1 semana atrás',
      weeksAgo: 'semanas atrás',
      monthAgo: '1 mês atrás',
      monthsAgo: 'meses atrás',
      yearAgo: '1 ano atrás',
      yearsAgo: 'anos atrás',
      justNowCompact: 'agora',
      inSeconds: 'em {value} segundos',
      inMinutes: 'em {value} minutos',
      inHours: 'em {value} horas',
      inDays: 'em {value} dias',
      inWeeks: 'em {value} semanas',
      inMonths: 'em {value} meses',
      inYears: 'em {value} anos'
    },
    ar: {
      ...baseLanguage,
      justNow: 'الآن',
      secondsAgo: 'ثوانٍ مضت',
      minuteAgo: 'قبل دقيقة واحدة',
      minutesAgo: 'دقائق مضت',
      hourAgo: 'قبل ساعة واحدة',
      hoursAgo: 'ساعات مضت',
      yesterday: 'أمس',
      daysAgo: 'أيام مضت',
      weekAgo: 'قبل أسبوع واحد',
      weeksAgo: 'أسابيع مضت',
      monthAgo: 'قبل شهر واحد',
      monthsAgo: 'أشهر مضت',
      yearAgo: 'قبل عام واحد',
      yearsAgo: 'أعوام مضت',
      justNowCompact: 'الآن',
      inSeconds: 'بعد {value} ثوانٍ',
      inMinutes: 'بعد {value} دقائق',
      inHours: 'بعد {value} ساعات',
      inDays: 'بعد {value} أيام',
      inWeeks: 'بعد {value} أسابيع',
      inMonths: 'بعد {value} أشهر',
      inYears: 'بعد {value} أعوام'
    },
    hi: {
      ...baseLanguage,
      justNow: 'अभी',
      secondsAgo: 'सेकंड पहले',
      minuteAgo: '1 मिनट पहले',
      minutesAgo: 'मिनट पहले',
      hourAgo: '1 घंटे पहले',
      hoursAgo: 'घंटे पहले',
      yesterday: 'बिता कल',
      daysAgo: 'दिन पहले',
      weekAgo: '1 हफ़्ते पहले',
      weeksAgo: 'हफ़्ते पहले',
      monthAgo: '1 महीने पहले',
      monthsAgo: 'महीने पहले',
      yearAgo: '1 साल पहले',
      yearsAgo: 'साल पहले',
      justNowCompact: 'अभी',
      inSeconds: '{value} सेकंड में',
      inMinutes: '{value} मिनट में',
      inHours: '{value} घंटे में',
      inDays: '{value} दिनों में',
      inWeeks: '{value} हफ़्तों में',
      inMonths: '{value} महीनों में',
      inYears: '{value} साल में'
    },
    tr: {
      ...baseLanguage,
      justNow: 'şimdi',
      secondsAgo: 'saniye önce',
      minuteAgo: '1 dakika önce',
      minutesAgo: 'dakika önce',
      hourAgo: '1 saat önce',
      hoursAgo: 'saat önce',
      yesterday: 'Dün',
      daysAgo: 'gün önce',
      weekAgo: '1 hafta önce',
      weeksAgo: 'hafta önce',
      monthAgo: '1 ay önce',
      monthsAgo: 'ay önce',
      yearAgo: '1 yıl önce',
      yearsAgo: 'yıl önce',
      justNowCompact: 'şimdi',
      inSeconds: '{value} saniye sonra',
      inMinutes: '{value} dakika sonra',
      inHours: '{value} saat sonra',
      inDays: '{value} gün sonra',
      inWeeks: '{value} hafta sonra',
      inMonths: '{value} ay sonra',
      inYears: '{value} yıl sonra'
    },
    nl: {
      ...baseLanguage,
      justNow: 'zojuist',
      secondsAgo: 'seconden geleden',
      minuteAgo: '1 minuut geleden',
      minutesAgo: 'minuten geleden',
      hourAgo: '1 uur geleden',
      hoursAgo: 'uur geleden',
      yesterday: 'Gisteren',
      daysAgo: 'dagen geleden',
      weekAgo: '1 week geleden',
      weeksAgo: 'weken geleden',
      monthAgo: '1 maand geleden',
      monthsAgo: 'maanden geleden',
      yearAgo: '1 jaar geleden',
      yearsAgo: 'jaar geleden',
      justNowCompact: 'nu',
      inSeconds: 'over {value} seconden',
      inMinutes: 'over {value} minuten',
      inHours: 'over {value} uur',
      inDays: 'over {value} dagen',
      inWeeks: 'over {value} weken',
      inMonths: 'over {value} maanden',
      inYears: 'over {value} jaren'
    }
  };
  
  module.exports = languages;
