// all languages supported

const languages = {
    en: {
        justNow: 'just now',
        secondsAgo: 'seconds ago',
        minuteAgo: '1 minute ago',
        minutesAgo: 'minutes ago',
        hourAgo: '1 hour ago',
        hoursAgo: 'hours ago',
        yesterday: 'Yesterday',
        daysAgo: 'days ago',
        weekAgo: '1 week ago',
        weeksAgo: 'weeks ago',
        monthAgo: '1 month ago',
        monthsAgo: 'months ago',
        yearAgo: '1 year ago',
        yearsAgo: 'years ago',
        justNowCompact: 'now'
    },
    es: {
        justNow: 'justo ahora',
        secondsAgo: 'segundos atrás',
        minuteAgo: 'hace 1 minuto',
        minutesAgo: 'hace minutos',
        hourAgo: 'hace 1 hora',
        hoursAgo: 'hace horas',
        yesterday: 'Ayer',
        daysAgo: 'hace días',
        weekAgo: 'hace 1 semana',
        weeksAgo: 'hace semanas',
        monthAgo: 'hace 1 mes',
        monthsAgo: 'hace meses',
        yearAgo: 'hace 1 año',
        yearsAgo: 'hace años',
        justNowCompact: 'ahora'
    },
    fr: {
        justNow: 'juste maintenant',
        secondsAgo: 'il y a quelques secondes',
        minuteAgo: 'il y a 1 minute',
        minutesAgo: 'il y a quelques minutes',
        hourAgo: 'il y a 1 heure',
        hoursAgo: 'il y a quelques heures',
        yesterday: 'Hier',
        daysAgo: 'il y a quelques jours',
        weekAgo: 'il y a 1 semaine',
        weeksAgo: 'il y a quelques semaines',
        monthAgo: 'il y a 1 mois',
        monthsAgo: 'il y a quelques mois',
        yearAgo: 'il y a 1 an',
        yearsAgo: 'il y a quelques années',
        justNowCompact: 'mtn'
    },
    de: {
        justNow: 'gerade eben',
        secondsAgo: 'vor wenigen Sekunden',
        minuteAgo: 'vor 1 Minute',
        minutesAgo: 'vor einigen Minuten',
        hourAgo: 'vor 1 Stunde',
        hoursAgo: 'vor einigen Stunden',
        yesterday: 'Gestern',
        daysAgo: 'vor einigen Tagen',
        weekAgo: 'vor 1 Woche',
        weeksAgo: 'vor einigen Wochen',
        monthAgo: 'vor 1 Monat',
        monthsAgo: 'vor einigen Monaten',
        yearAgo: 'vor 1 Jahr',
        yearsAgo: 'vor einigen Jahren',
        justNowCompact: 'jetzt'
    },
    it: {
        justNow: 'proprio ora',
        secondsAgo: 'alcuni secondi fa',
        minuteAgo: '1 minuto fa',
        minutesAgo: 'alcuni minuti fa',
        hourAgo: '1 ora fa',
        hoursAgo: 'alcune ore fa',
        yesterday: 'Ieri',
        daysAgo: 'alcuni giorni fa',
        weekAgo: '1 settimana fa',
        weeksAgo: 'alcune settimane fa',
        monthAgo: '1 mese fa',
        monthsAgo: 'alcuni mesi fa',
        yearAgo: '1 anno fa',
        yearsAgo: 'alcuni anni fa',
        justNowCompact: 'ora'
    },
    ja: {
        justNow: 'たった今',
        secondsAgo: '数秒前',
        minuteAgo: '1 分前',
        minutesAgo: '数分前',
        hourAgo: '1 時間前',
        hoursAgo: '数時間前',
        yesterday: '昨日',
        daysAgo: '数日前',
        weekAgo: '1 週間前',
        weeksAgo: '数週間前',
        monthAgo: '1 か月前',
        monthsAgo: '数か月前',
        yearAgo: '1 年前',
        yearsAgo: '数年前',
        justNowCompact: '今'
    },
    zh: {
        justNow: '刚刚',
        secondsAgo: '几秒前',
        minuteAgo: '1 分钟前',
        minutesAgo: '几分钟前',
        hourAgo: '1 小时前',
        hoursAgo: '几小时前',
        yesterday: '昨天',
        daysAgo: '几天前',
        weekAgo: '1 周前',
        weeksAgo: '几周前',
        monthAgo: '1 个月前',
        monthsAgo: '几个月前',
        yearAgo: '1 年前',
        yearsAgo: '几年前',
        justNowCompact: '现在'
    },
    ru: {
        justNow: 'только что',
        secondsAgo: 'несколько секунд назад',
        minuteAgo: '1 минуту назад',
        minutesAgo: 'несколько минут назад',
        hourAgo: '1 час назад',
        hoursAgo: 'несколько часов назад',
        yesterday: 'Вчера',
        daysAgo: 'несколько дней назад',
        weekAgo: '1 неделю назад',
        weeksAgo: 'несколько недель назад',
        monthAgo: '1 месяц назад',
        monthsAgo: 'несколько месяцев назад',
        yearAgo: '1 год назад',
        yearsAgo: 'несколько лет назад',
        justNowCompact: 'сейчас'
    },
    pt: {
        justNow: 'agora mesmo',
        secondsAgo: 'alguns segundos atrás',
        minuteAgo: 'há 1 minuto',
        minutesAgo: 'minutos atrás',
        hourAgo: 'há 1 hora',
        hoursAgo: 'horas atrás',
        yesterday: 'Ontem',
        daysAgo: 'dias atrás',
        weekAgo: 'há 1 semana',
        weeksAgo: 'semanas atrás',
        monthAgo: 'há 1 mês',
        monthsAgo: 'meses atrás',
        yearAgo: 'há 1 ano',
        yearsAgo: 'anos atrás',
        justNowCompact: 'agora'
    },
    ar: {
        justNow: 'الآن',
        secondsAgo: 'قبل بضع ثوانٍ',
        minuteAgo: 'قبل دقيقة واحدة',
        minutesAgo: 'منذ دقائق',
        hourAgo: 'قبل ساعة واحدة',
        hoursAgo: 'منذ ساعات',
        yesterday: 'أمس',
        daysAgo: 'منذ أيام',
        weekAgo: 'قبل أسبوع واحد',
        weeksAgo: 'منذ أسابيع',
        monthAgo: 'قبل شهر واحد',
        monthsAgo: 'منذ أشهر',
        yearAgo: 'قبل عام واحد',
        yearsAgo: 'منذ أعوام',
        justNowCompact: 'الآن'
    },
    hi: {
        justNow: 'अभी',
        secondsAgo: 'कुछ सेकंड पहले',
        minuteAgo: '1 मिनट पहले',
        minutesAgo: 'कुछ मिनट पहले',
        hourAgo: '1 घंटे पहले',
        hoursAgo: 'कुछ घंटे पहले',
        yesterday: 'बिता कल',
        daysAgo: 'कुछ दिन पहले',
        weekAgo: '1 हफ़्ते पहले',
        weeksAgo: 'कुछ हफ़्ते पहले',
        monthAgo: '1 महीने पहले',
        monthsAgo: 'कुछ महीने पहले',
        yearAgo: '1 साल पहले',
        yearsAgo: 'कुछ साल पहले',
        justNowCompact: 'अभी'
    },
    tr: {
        justNow: 'şimdi',
        secondsAgo: 'birkaç saniye önce',
        minuteAgo: '1 dakika önce',
        minutesAgo: 'birkaç dakika önce',
        hourAgo: '1 saat önce',
        hoursAgo: 'birkaç saat önce',
        yesterday: 'Dün',
        daysAgo: 'birkaç gün önce',
        weekAgo: '1 hafta önce',
        weeksAgo: 'birkaç hafta önce',
        monthAgo: '1 ay önce',
        monthsAgo: 'birkaç ay önce',
        yearAgo: '1 yıl önce',
        yearsAgo: 'birkaç yıl önce',
        justNowCompact: 'şimdi'
    },
    nl: {
        justNow: 'zojuist',
        secondsAgo: 'enkele seconden geleden',
        minuteAgo: '1 minuut geleden',
        minutesAgo: 'enkele minuten geleden',
        hourAgo: '1 uur geleden',
        hoursAgo: 'enkele uren geleden',
        yesterday: 'Gisteren',
        daysAgo: 'enkele dagen geleden',
        weekAgo: '1 week geleden',
        weeksAgo: 'enkele weken geleden',
        monthAgo: '1 maand geleden',
        monthsAgo: 'enkele maanden geleden',
        yearAgo: '1 jaar geleden',
        yearsAgo: 'enkele jaren geleden',
        justNowCompact: 'nu'
    }
};

module.exports = languages;
